In [64]:
import csv
with open("data.csv","w",newline="") as file:
    writer=csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["tulasi","20","Vijayawada"])
    writer.writerow(["vijju","18","Hyderabad"])

In [65]:
import csv
with open("data.csv","r") as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['tulasi', '20', 'Vijayawada']
['vijju', '18', 'Hyderabad']


In [66]:
import numpy as np

In [67]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [68]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [69]:
l=range(1000)
%timeit [i**2 for i in l]

120 μs ± 3.48 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [70]:
a=np.arange(1000)
%timeit a**2

2.21 μs ± 404 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## CREATING ARRAYS

In [71]:
a=np.array([1,2,3,4]) #one dimensional array or vectors

In [72]:
print(a.ndim)

1


In [73]:
b=np.array([[1,2,3],[4,5,5]]) #two dimensional array or matrix
print(b)

[[1 2 3]
 [4 5 5]]


In [74]:
print(b.ndim)

2


In [75]:
c=np.array([[[1,2],[3,4]],[[4,5],[6,7]]]) #3 dimensional (in cube)
print(c)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
3


In [76]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 2)


## FUNCTIONS FOR CREATING ARRAY

In [77]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [78]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [79]:
#using linspace
a=np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [80]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [81]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [82]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [83]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [84]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [85]:
print(np.diag(a))

[1 2 3 4]


## BASIC DATA TYPES

In [86]:
a=np.arange(10)
print(a.dtype)

int64


In [87]:
a=np.arange(10,dtype="float")
print(a.dtype)

float64


In [88]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


## OTHER DATA TYPES

In [89]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [90]:
a=np.array([True,False])
print(a.dtype)

bool


In [91]:
a=np.array(["aditya degree college"])
print(a.dtype) #unicode string type

<U21


## INDEXING AND SLICING

In [92]:
a=np.arange(10)
print(a[5])

5


In [93]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [94]:
print(a[0,0])

1


In [95]:
b=np.arange(1,10)
print(b[2:5])

[3 4 5]


## SLICING

In [33]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(a[1:8:3])

[1 4 7]


In [35]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [36]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [37]:
a[1,1]=5
print(a)

[[1 0 0]
 [0 5 0]
 [0 0 3]]


In [38]:
a=np.arange(10)
a[4:]=9
a

array([0, 1, 2, 3, 9, 9, 9, 9, 9, 9])

## COPYING AND VIEWING

In [39]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [40]:
print(np.shares_memory(a,b))

True


In [41]:
b[0]=10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [42]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [43]:
print(np.shares_memory(a,b))

False


In [44]:
print(b.base)

None


## RANDOM NUMBER GENERATION

In [45]:
import numpy as np
a=np.random.randint(0,20,15)
print(a)

[18 12  3 10  7  8 12 14 15  1 12  1  9  5  4]


In [46]:
mask=(a%2==0)
new_a=a[mask]
print(new_a)

[18 12 10  8 12 14 12  4]


In [47]:
a[mask]=-1
print(a)

[-1 -1  3 -1  7 -1 -1 -1 15  1 -1  1  9  5 -1]


## ELEMENT WISE OPERATIONS
## BASIC OPERATION

In [48]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [49]:
print(a**2)

[ 1  4  9 16]


## ALL ARITHMETIC OPERATES ELEMENT WISE

In [50]:
b=np.ones(4) +1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [51]:
print(a*b)

[2. 4. 6. 8.]


In [52]:
c=np.diag([1,2,3,4])
print(c)
print(c *c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [53]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## COMPARISON OPERATOR

In [54]:
a=np.array([1,2,6])
b=np.array([4,5,6])
print(a==b)

[False False  True]


In [55]:
print(a<b)

[ True  True False]


In [56]:
print(a>b)

[False False False]


In [57]:
# array wise comparision
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,c))

True


## LOGICAL OPERATOR

In [58]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [59]:
print(np.logical_and(a,b))

[ True False False False]


In [60]:
print(np.logical_not(a))

[False  True False  True]


## TRIGNOMETRY/TRANSCENDENTAL FUNCTIONS

In [61]:
a=np.arange(4)
print(a)

[0 1 2 3]


In [62]:
print(np.sin(a))

[0.         0.84147098 0.90929743 0.14112001]


In [63]:
np.log(a)

C:\Users\Tulasi\AppData\Local\Temp\ipykernel_1508\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229])